### ISSUE TITLE
Additional functionality

### ISSUE THREAD

**Issue by Yodesman** [ZakFahey/SmartRegions#2]
-Display total pages of smartregions that exist when "/smartregion list" is used
-List the smartregions alphabetically rather than by date of creation when "/smartregion list" is used
-Optional parameter for "/smartregion list" for only displaying smartregions within a certain radius of the player. e.g. "/smartregion list 200" would only list the smartregions that are within 200 blocks of the player

**Comment by ZakFahey** [comment]
@Yodesman I just implemented the changes
